server:
  port: 8080
#  servlet:
#    context-path: /kapyweb

spring:
  datasource:
    url: jdbc:mysql://root:QOJGvGzDBYPUiANvDuGkJVrjFjxQWRCc@centerbeam.proxy.rlwy.net:16763/railway
    username: root
    password: QOJGvGzDBYPUiANvDuGkJVrjFjxQWRCc
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_CONNECTION:0909Kapibala@gmail.com}
    password: ${EMAIL_PASSWORD:ymijqxcirmyqnerh}
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                   enable: true
                ssl:
                  enable: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "vF2Gndy26DaqK94eN4mWDPvQEatpbXuIuBOLcs+RM1C1mRvf8905iOVjpgtwg90D"
  valid-duration: 3600
  refreshable-duration: 604800

logging:
  level:
    org.springframework.mail: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # Default path, no need to prefix with /kapyweb
  swagger-ui:
    enabled: true
    path: /swagger-ui   # Default path, no need to prefix with /kapyweb
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha